### ISSUE TITLE
More styling options for input and keyboard image missing

### ISSUE THREAD

**Issue by nanchu** [ajimix/Input-Framer#34]
I can't style the text inside the input to not be underlined or to change the caret color. The keyboard image also appears to be missing for me.

**Comment by ajimix** [comment]
Hello @nanchu the keyboard image missing is because you didn't download the whole project, so the image is missing. Make sure you download the image file and you put it inside the modules folder.

Styling the input is pretty easy, you can do it like the following:

```coffeescript
input = new InputModule.Input
  ....

input.style =
  fontSize: "30px"
  lineHeight: "30px"
  caretColor: "red"
  padding: "10px"
  color: "white"
  ...
```

I'll close the issue, please reopen if you need more help
